# Generated by Django 5.0 on 2024-02-17 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='voter',
            table='voter',
        ),
    ]
