# Generated by Django 5.0 on 2024-02-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_voter_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='is_admin',
        ),
    ]
