# Generated by Django 5.0 on 2024-01-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_userprofile_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vote',
            field=models.IntegerField(default=-1),
        ),
    ]
