# Generated by Django 5.0 on 2024-02-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_remove_voter_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_voted',
            field=models.BooleanField(default=False),
        ),
    ]
